{% set name = "osm2pgrouting" %}
{% set version = "2.3.8" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source: 
  url: https://github.com/pgRouting/osm2pgrouting/archive/v{{ version }}.tar.gz
  sha256: e3a58bcacf0c8811e0dcf3cf3791a4a7cc5ea2a901276133eacf227b30fd8355

build:
  number: 3
  skip: true  # [not linux]
  script:
    - |
      cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=$PREFIX
      cd build/
      make 
      make install
  missing_dso_whitelist:
    - /lib64/libm.so.6
    - /lib64/libc.so.6

requirements:
  host:
    - cmake
    - make
    - vcpkg
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - expat
    - libboost-devel
    - libpq
    - libpqxx

  run:

test:
  commands:
    - osm2pgrouting --version

about:
  home: https://github.com/pgRouting/osm2pgrouting
  summary: |
    pgRouting extends the PostGIS / PostgreSQL geospatial database to provide geospatial routing functionality.
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
